# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json if available
COPY package*.json ./

# Install app dependencies
RUN npm install --production

# Bundle app source
COPY . .

# Expose port if needed (default 3000, but MCP may use different)
EXPOSE 3000

# Run the MCP server
CMD [ "npm", "run", "mcp" ]
